import { X, Copy, Check } from 'lucide-react';
import { useState } from 'react';

interface SectionData {
  title: string;
  content: string;
  missing: string[];
  enhancements: Array<{ text: string; source: string }>;
  questions: string[];
}

interface KeyInfo {
  client: string;
  jobToBeDone: string;
  budget: string;
  dueDate: string;
  liveDate: string;
  campaignDuration: string;
  briefLevel: string;
}

interface ExportBriefModalProps {
  onClose: () => void;
  sections: SectionData[];
  keyInfo: KeyInfo;
  leadDepartment: string;
  supportingDepartments: string[];
}

export function ExportBriefModal({ 
  onClose, 
  sections, 
  keyInfo, 
  leadDepartment, 
  supportingDepartments 
}: ExportBriefModalProps) {
  const [copied, setCopied] = useState(false);

  // Strip HTML tags from content for plain text export
  const stripHtml = (html: string) => {
    const tmp = document.createElement('div');
    tmp.innerHTML = html;
    return tmp.textContent || tmp.innerText || '';
  };

  const generateExportText = () => {
    let text = `ENHANCED BRIEF - ${keyInfo.client}\n`;
    text += `${'='.repeat(60)}\n\n`;
    
    text += `KEY INFORMATION\n`;
    text += `${'-'.repeat(60)}\n`;
    text += `Client: ${keyInfo.client}\n`;
    text += `Job to be Done: ${keyInfo.jobToBeDone}\n`;
    text += `Budget: ${keyInfo.budget}\n`;
    text += `Due Date: ${keyInfo.dueDate}\n`;
    text += `Live Date: ${keyInfo.liveDate}\n`;
    text += `Campaign Duration: ${keyInfo.campaignDuration}\n`;
    text += `Brief Level: ${keyInfo.briefLevel}\n\n`;
    
    text += `DEPARTMENT ASSIGNMENTS\n`;
    text += `${'-'.repeat(60)}\n`;
    text += `Lead Department: ${leadDepartment}\n`;
    text += `Supporting Departments: ${supportingDepartments.join(', ')}\n\n`;

    sections.forEach((section, index) => {
      text += `${'='.repeat(60)}\n`;
      text += `${index + 1}. ${section.title.toUpperCase()}\n`;
      text += `${'='.repeat(60)}\n\n`;
      text += `${stripHtml(section.content)}\n\n`;
    });

    text += `${'='.repeat(60)}\n`;
    text += `End of Brief\n`;
    text += `Generated by Bastion OS\n`;
    
    return text;
  };

  const handleCopy = async () => {
    const text = generateExportText();
    try {
      if (navigator.clipboard && navigator.clipboard.writeText) {
        await navigator.clipboard.writeText(text);
        setCopied(true);
        setTimeout(() => setCopied(false), 2000);
      } else {
        fallbackCopyTextToClipboard(text);
        setCopied(true);
        setTimeout(() => setCopied(false), 2000);
      }
    } catch (err) {
      fallbackCopyTextToClipboard(text);
      setCopied(true);
      setTimeout(() => setCopied(false), 2000);
    }
  };

  const fallbackCopyTextToClipboard = (text: string) => {
    const textArea = document.createElement('textarea');
    textArea.value = text;
    textArea.style.position = 'fixed';
    textArea.style.left = '-999999px';
    textArea.style.top = '-999999px';
    document.body.appendChild(textArea);
    textArea.focus();
    textArea.select();
    try {
      document.execCommand('copy');
    } catch (err) {
      console.error('Fallback: Oops, unable to copy', err);
    }
    document.body.removeChild(textArea);
  };

  return (
    <div className="fixed inset-0 bg-black bg-opacity-50 flex items-center justify-center z-50 p-4">
      <div className="bg-white rounded-2xl shadow-2xl max-w-4xl w-full max-h-[90vh] flex flex-col">
        {/* Header */}
        <div className="flex items-center justify-between p-6 border-b border-gray-200">
          <div>
            <h2 className="mb-1">Export Brief</h2>
            <p className="text-sm text-gray-600">Copy the brief content below</p>
          </div>
          <button
            onClick={onClose}
            className="text-gray-400 hover:text-gray-600 transition-colors"
          >
            <X className="w-6 h-6" />
          </button>
        </div>

        {/* Content */}
        <div className="flex-1 overflow-y-auto p-6">
          <div className="bg-gray-50 rounded-lg p-6 font-mono text-sm whitespace-pre-wrap break-words">
            {generateExportText()}
          </div>
        </div>

        {/* Footer */}
        <div className="p-6 border-t border-gray-200 bg-gray-50">
          <div className="flex gap-3 justify-end">
            <button
              onClick={onClose}
              className="px-6 py-3 bg-white border border-gray-300 rounded-lg hover:bg-gray-50 transition-colors"
            >
              Close
            </button>
            <button
              onClick={handleCopy}
              className="px-6 py-3 bg-black text-white rounded-lg hover:bg-gray-800 transition-colors flex items-center gap-2"
            >
              {copied ? (
                <>
                  <Check className="w-4 h-4" />
                  Copied!
                </>
              ) : (
                <>
                  <Copy className="w-4 h-4" />
                  Copy to Clipboard
                </>
              )}
            </button>
          </div>
        </div>
      </div>
    </div>
  );
}