#!/usr/bin/env python3
"""
Extract section templates from the Bastion OS Brief Sections spreadsheet
and generate a SQL migration file.

Usage:
    python3 scripts/extract-spreadsheet.py

Reads: docs/Bastion OS Brief Sections.xlsx (sheet: "Formatted Brief Sections")
Writes: stdout (SQL INSERT statements)
"""

import json
import re
import sys
import openpyxl

XLSX_PATH = "docs/Bastion OS Brief Sections.xlsx"
SHEET_NAME = "Formatted Brief Sections"

# Column mapping (1-indexed)
COL_NAME = 1
COL_CATEGORY = 2
COL_DESCRIPTION = 3
COL_INCLUDE = 4
# LLM Validation Prompts per practice area
PRACTICE_COLUMNS = {
    "Creative": 5,        # E
    "Design": 6,          # F
    "Corporate Comms": 7, # G
    "Consumer PR": 8,     # H
    "Activations": 9,     # I
}

DATA_START_ROW = 3
DATA_END_ROW = 29  # 27 sections


def slugify(name: str) -> str:
    """Convert section name to a URL-safe slug ID."""
    s = name.lower().strip()
    s = re.sub(r"[()']", "", s)
    s = re.sub(r"[^a-z0-9]+", "-", s)
    s = s.strip("-")
    return s


def escape_sql(value: str | None) -> str:
    """Escape a string for SQL single-quote literals."""
    if value is None:
        return "NULL"
    escaped = value.replace("'", "''")
    return f"'{escaped}'"


def main():
    wb = openpyxl.load_workbook(XLSX_PATH, data_only=True)
    ws = wb[SHEET_NAME]

    rows = []
    for row_idx in range(DATA_START_ROW, DATA_END_ROW + 1):
        name = ws.cell(row_idx, COL_NAME).value
        if not name:
            continue

        category = ws.cell(row_idx, COL_CATEGORY).value
        description = ws.cell(row_idx, COL_DESCRIPTION).value
        include_in = ws.cell(row_idx, COL_INCLUDE).value
        slug = slugify(name)

        # Build practice_prompts JSONB
        practice_prompts = {}
        for practice_name, col_idx in PRACTICE_COLUMNS.items():
            prompt = ws.cell(row_idx, col_idx).value
            if prompt and str(prompt).strip():
                practice_prompts[practice_name] = str(prompt).strip()

        rows.append({
            "id": slug,
            "name": name.strip(),
            "category": category.strip() if category else None,
            "description": description.strip() if description else None,
            "include_in": include_in.strip() if include_in else None,
            "practice_prompts": practice_prompts if practice_prompts else None,
        })

    # Generate SQL
    print("-- Generated by scripts/extract-spreadsheet.py")
    print(f"-- {len(rows)} section templates from {XLSX_PATH}")
    print()
    print("INSERT INTO section_templates (id, organisation_id, name, description, category, ai_evaluation_criteria, practice_prompts)")
    print("VALUES")

    value_lines = []
    for r in rows:
        pp_sql = escape_sql(json.dumps(r["practice_prompts"], ensure_ascii=False)) if r["practice_prompts"] else "NULL"
        line = f"  ({escape_sql(r['id'])}, NULL, {escape_sql(r['name'])}, {escape_sql(r['description'])}, {escape_sql(r['category'])}, NULL, {pp_sql})"
        value_lines.append(line)

    print(",\n".join(value_lines) + ";")

    # Summary to stderr
    prompt_count = sum(
        len(r["practice_prompts"]) for r in rows if r["practice_prompts"]
    )
    print(f"\n-- Summary: {len(rows)} sections, {prompt_count} practice-specific prompts", file=sys.stderr)

    # Also output the section mapping table for reference
    print("\n-- Section mapping reference:", file=sys.stderr)
    print(f"-- {'ID':<30} {'Name':<30} {'Category':<20} {'Include in'}", file=sys.stderr)
    for r in rows:
        print(f"-- {r['id']:<30} {r['name']:<30} {(r['category'] or ''):<20} {r['include_in'] or ''}", file=sys.stderr)


if __name__ == "__main__":
    main()
